# Generated by Django 4.0 on 2021-12-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('field_id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('box_office', models.BigIntegerField(blank=True, db_column='Box_office', null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=255, null=True)),
                ('rated', models.CharField(blank=True, db_column='Rated', max_length=255, null=True)),
                ('imdbid', models.IntegerField(blank=True, db_column='imdbID', null=True)),
                ('awards', models.CharField(blank=True, db_column='Awards', max_length=255, null=True)),
                ('poster', models.CharField(blank=True, db_column='Poster', max_length=255, null=True)),
                ('director', models.CharField(blank=True, db_column='Director', max_length=255, null=True)),
                ('released', models.CharField(blank=True, db_column='Released', max_length=255, null=True)),
                ('writer', models.CharField(blank=True, db_column='Writer', max_length=1024, null=True)),
                ('imdbvotes', models.IntegerField(blank=True, db_column='imdbVotes', null=True)),
                ('runtime', models.CharField(blank=True, db_column='Runtime', max_length=255, null=True)),
                ('imdbrating', models.FloatField(blank=True, db_column='IMdbRating', null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('metascore', models.IntegerField(blank=True, db_column='Metascore', null=True)),
            ],
            options={
                'db_table': 'film',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('field_id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('movie', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('field_id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('movie', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'favorite',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('field_id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('movie', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'history',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('field_id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('movie', models.CharField(blank=True, max_length=255, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('star', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.TextField()),
                ('mail', models.CharField(blank=True, max_length=255, null=True)),
                ('head_portrait', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'username',
                'managed': True,
            },
        ),
    ]
