# Generated by Django 4.0 on 2021-12-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='username',
            options={'managed': False},
        ),
    ]
