# Generated by Django 4.0 on 2022-01-02 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_time', models.DateTimeField(default=datetime.datetime(2022, 1, 2, 13, 58, 4, 241114), verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '2. 邮箱验证码',
                'verbose_name_plural': '2. 邮箱验证码',
            },
        ),
    ]
