# Generated by Django 4.0 on 2022-01-08 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_emailverifyrecord_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 22, 42, 31, 70330), verbose_name='发送时间'),
        ),
    ]
