<<<<<<< HEAD
# Generated by Django 3.2.10 on 2022-01-03 15:37
=======
# Generated by Django 4.0 on 2022-01-08 14:43
>>>>>>> bb807b22e7e5dbb0ece8ef34acdc486c3b25d636

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_emailverifyrecord_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 23, 37, 18, 135916), verbose_name='发送时间'),
=======
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 22, 43, 21, 988085), verbose_name='发送时间'),
>>>>>>> bb807b22e7e5dbb0ece8ef34acdc486c3b25d636
        ),
    ]
