# Generated by Django 4.0 on 2022-01-08 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_emailverifyrecord_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 22, 43, 36, 334346), verbose_name='发送时间'),
        ),
    ]
