# Generated by Django 3.2.10 on 2022-01-03 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_emailverifyrecord_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 0, 8, 9, 234522), verbose_name='发送时间'),
        ),
    ]
