# Generated by Django 4.0 on 2022-01-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_emailverifyrecord_send_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailverifyrecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('send_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_emailverifyrecord',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EmailVerifyRecord',
        ),
    ]
