# Generated by Django 4.0 on 2021-12-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_detail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('field_id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('imdbid', models.CharField(blank=True, max_length=255, null=True)),
                ('imdb_country', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
    ]
