# Generated by Django 4.0 on 2022-01-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
